import styles from "@/styles/Home.module.css";
import axios from "axios";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [lista, setLista] = useState([]);
  const [user, setUser] = useState({
    nome: "",
    email: "",
  });

  function handleChange(e) {
    setUser({ ...user, [e.target.name]: e.target.value });
  }

  function renderizaItens() {
    return lista.map((i) => (
      <div className={styles.items} key={i.id}>
        <p className={styles.item}>{i.nome}</p>
        <p className={styles.item}>{i.email}</p>
        <p className={styles.opcoes}>
          <button className={styles.buttonVer} onClick={() => ver(i.id)}>
            Ver
          </button>
          <button className={styles.buttonEditar} onClick={() => editar(i.id)}>
            Editar
          </button>
          <button
            className={styles.buttonDeletar}
            onClick={() => deletar(i.id)}
          >
            Deletar
          </button>
        </p>
      </div>
    ));
  }

  function deletar(id) {
    alert("selecionou deletar");
  }

  function editar(id) {
    alert("selecionou editar");
  }

  function ver(id) {
    alert("selecionou ver");
  }

  function adicionar() {
    axios
      .post("https://api-crud-dnla.onrender.com/user",user)
      .then((res) => {
        buscarLista();
      })
      .catch((err) => {
        console.log(err);
      });
  }

  function buscarLista() {
    axios
      .get("https://api-crud-dnla.onrender.com/users")
      .then((res) => {
        setLista(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  }

  useEffect(() => {
    buscarLista();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.titulo}>Minha Aplicação</h1>
        <div className={styles.tabela}>
          <div className={styles.header}>
            <h2 className={styles.tituloTabela}>Lista</h2>
            <form>
              <input
                className={styles.input}
                type="text"
                name="nome"
                placeholder="Nome"
                onChange={handleChange}
              />
              <input
                className={styles.input}
                type="text"
                name="email"
                placeholder="Email"
                onChange={handleChange}
              />
              <button className={styles.buttonAdicionar} onClick={adicionar}>
                Adicionar
              </button>
            </form>
          </div>
          <div className={styles.items}>
            <p className={styles.item}>Nome</p>
            <p className={styles.item}>Email</p>
            <p className={styles.item}>Opções</p>
          </div>
          {lista.lenght > 0 ? renderizaItens() : <>Nenhum usuário encontrado</>}
        </div>
      </main>
    </>
  );
}
