import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [lista, setLista] = useState([
    {
      id: 1,
      nome: "item1",
      preco: 33,
    },
    {
      id: 2,
      nome: "item2",
      preco: 55,
    },
  ]);

  function renderizaItens() {
    return lista.map((i) => (
      <div className={styles.items}>
        <p className={styles.item}>{i.nome}</p>
        <p className={styles.item}>R$ {i.preco}</p>
        <p className={styles.opcoes}>
          <button className={styles.buttonVer} onClick={() => ver(i.id)}>Ver</button>
          <button className={styles.buttonEditar} onClick={() => editar(i.id)}>Editar</button>
          <button className={styles.buttonDeletar} onClick={() => deletar(i.id)}>Deletar</button>
        </p>
      </div>
    ));
  }

  function deletar() {
    alert("selecionou deletar");
  }

  function editar() {
    alert("selecionou editar");
  }

  function ver() {
    alert("selecionou ver");
  }

  function adicionar() {
    alert("selecionou adicionar");
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.titulo}>Minha Aplicação</h1>
        <div className={styles.tabela}>
          <h2 className={styles.tituloTabela}>Lista</h2>
          <div className={styles.items}>
            <p className={styles.item}>Nome</p>
            <p className={styles.item}>Preço (R$)</p>
            <p className={styles.item}>Opções</p>
          </div>
          {renderizaItens()}
        </div>
      </main>
    </>
  );
}
